version: "3.8"

services:
  rabbitmq:
    mem_limit: 512m
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
  redis:
    mem_limit: 256m
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
  ws:
    mem_limit: 1g
    cpus: "2.0"
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "${C2C_WS_PORT:-8080}:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # GRADLE_USER_HOME: /tmp/gradle
    depends_on:
      - rabbitmq
      - redis
    command: ["bash", "-lc", "sleep infinity"]
    stdin_open: true
    tty: true


    csm:
      mem_limit: 1g
      cpus: "2.0"
      build:
        context: ../c2c-csm-k3s
        dockerfile: Dockerfile.dev
      working_dir: /workspace
      volumes:
        - ../c2c-csm-k3s:/workspace
      ports:
        - "${C2C_CSM_PORT:-8081}:8080"
      environment:
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672
        SPRING_RABBITMQ_USERNAME: guest
        SPRING_RABBITMQ_PASSWORD: guest
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
      depends_on:
        - rabbitmq
        - redis
      command: ["bash", "-lc", "sleep infinity"]
      stdin_open: true
      tty: true
